projects:
  ElastiLodgeApi:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: eenhx3rttvemhcqoc4oj6s5ktq
        codeGenTarget: swift
        generatedFileName: GeneratedAPI.swift
        docsFilePath: graphql
        region: eu-west-1
      endpoints:
        prod: >-
          https://sdg3eqqcm5bdlib6hqb6izdi5i.appsync-api.eu-west-1.amazonaws.com/graphql
